### ISSUE TITLE
License missing 😟

### ISSUE THREAD

**Issue by dpshelio** [davidhenty/sharpen#1]
Can we use this for teaching? As it's now you own all the ©, so everyone would need to ask you permission to use it.

**Comment by davidhenty** [comment]
I just chucked the code onto github the other day so Heather Kelly at UCL could see it (I guess that's how you came across it). I'll put a licence up as well so it can be used freely for teaching. The code's a bit of a mess at present - in fact, I just noticed that it's an old version that has some uninitialised arrays in it which needs to be fixed ASAP!
